"""
Test script to verify retry logic and fallback chains actually work.
Run: python MARKETING_TEAM/tools/test_reliability.py
"""
import asyncio
import sys
import os
from pathlib import Path
from unittest.mock import AsyncMock, patch, MagicMock

# Setup path so we can import the MCP server
sys.path.insert(0, str(Path(__file__).parent.parent))
os.chdir(str(Path(__file__).parent.parent))

from dotenv import load_dotenv
load_dotenv(Path(__file__).parent.parent / '.env')


def test_imports():
    """Test 1: Can we import the packages?"""
    print("\n=== TEST 1: Package Imports ===")
    try:
        import tenacity
        from loguru import logger
        print(f"  tenacity: installed")
        print(f"  loguru:   installed")
        print("  PASS")
        return True
    except ImportError as e:
        print(f"  FAIL: {e}")
        return False


def test_retry_decorators():
    """Test 2: Are retry decorators on all 7 functions?"""
    print("\n=== TEST 2: Retry Decorators ===")
    from tools.mcp_server import (
        generate_gpt4o_image_mcp,
        generate_sora_video_mcp,
        analyze_ugc_image_mcp,
        generate_nano_banana_image_mcp,
        generate_nano_banana_2_image_mcp,
        generate_veo_text_to_video_mcp,
        generate_veo_ugc_from_image_mcp,
    )

    functions = {
        "generate_gpt4o_image_mcp": generate_gpt4o_image_mcp,
        "generate_sora_video_mcp": generate_sora_video_mcp,
        "analyze_ugc_image_mcp": analyze_ugc_image_mcp,
        "generate_nano_banana_image_mcp": generate_nano_banana_image_mcp,
        "generate_nano_banana_2_image_mcp": generate_nano_banana_2_image_mcp,
        "generate_veo_text_to_video_mcp": generate_veo_text_to_video_mcp,
        "generate_veo_ugc_from_image_mcp": generate_veo_ugc_from_image_mcp,
    }

    all_pass = True
    for name, fn in functions.items():
        has_retry = hasattr(fn, 'retry')
        status = "PASS" if has_retry else "FAIL"
        print(f"  {name}: @retry {'found' if has_retry else 'MISSING'} [{status}]")
        if not has_retry:
            all_pass = False

    print(f"  {'PASS' if all_pass else 'FAIL'} - {len(functions)} functions checked")
    return all_pass


def test_retry_actually_retries():
    """Test 3: Does retry actually retry on failure?"""
    print("\n=== TEST 3: Retry Actually Fires ===")
    from tenacity import retry, stop_after_attempt, wait_exponential, retry_if_exception_type

    call_count = 0

    @retry(
        stop=stop_after_attempt(3),
        wait=wait_exponential(multiplier=0.1, min=0.1, max=0.5),  # Fast for testing
        retry=retry_if_exception_type((Exception,)),
        reraise=True
    )
    async def flaky_function():
        nonlocal call_count
        call_count += 1
        if call_count < 3:
            raise ConnectionError(f"Simulated failure #{call_count}")
        return "success on attempt 3"

    result = asyncio.run(flaky_function())

    if call_count == 3 and result == "success on attempt 3":
        print(f"  Function called {call_count} times (failed 2, succeeded on 3rd)")
        print(f"  Result: {result}")
        print("  PASS - Retry logic works correctly")
        return True
    else:
        print(f"  FAIL - Expected 3 calls, got {call_count}")
        return False


def test_retry_gives_up_after_max():
    """Test 4: Does retry stop after max attempts?"""
    print("\n=== TEST 4: Retry Gives Up After Max ===")
    from tenacity import retry, stop_after_attempt, wait_exponential, retry_if_exception_type

    call_count = 0

    @retry(
        stop=stop_after_attempt(3),
        wait=wait_exponential(multiplier=0.1, min=0.1, max=0.5),
        retry=retry_if_exception_type((Exception,)),
        reraise=True
    )
    async def always_fails():
        nonlocal call_count
        call_count += 1
        raise ConnectionError(f"Permanent failure #{call_count}")

    try:
        asyncio.run(always_fails())
        print("  FAIL - Should have raised exception")
        return False
    except ConnectionError:
        if call_count == 3:
            print(f"  Function called {call_count} times then gave up")
            print(f"  Original exception re-raised correctly")
            print("  PASS - Max retry limit works")
            return True
        else:
            print(f"  FAIL - Expected 3 calls, got {call_count}")
            return False


def test_fallback_chain():
    """Test 5: Does the fallback chain cascade correctly?"""
    print("\n=== TEST 5: Image Fallback Chain ===")
    from mcp.types import TextContent

    call_log = []

    async def mock_nano2(*args, **kwargs):
        call_log.append("Nano Banana 2")
        raise Exception("Google API down")

    async def mock_nanopro(*args, **kwargs):
        call_log.append("Nano Banana Pro")
        raise Exception("Google API still down")

    async def mock_gpt4o(*args, **kwargs):
        call_log.append("GPT-4o")
        return [TextContent(type="text", text="Generated by GPT-4o fallback")]

    with patch('tools.mcp_server.generate_nano_banana_2_image_mcp', mock_nano2), \
         patch('tools.mcp_server.generate_nano_banana_image_mcp', mock_nanopro), \
         patch('tools.mcp_server.generate_gpt4o_image_mcp', mock_gpt4o):

        from tools.mcp_server import generate_image_with_fallback
        result = asyncio.run(generate_image_with_fallback(
            prompt="test", aspect_ratio="16:9", filename="test.png"
        ))

    if call_log == ["Nano Banana 2", "Nano Banana Pro", "GPT-4o"]:
        print(f"  Call order: {' -> '.join(call_log)}")
        print(f"  Final result from: GPT-4o (3rd provider)")
        print("  PASS - Fallback chain cascades correctly")
        return True
    else:
        print(f"  FAIL - Unexpected call order: {call_log}")
        return False


def test_video_fallback_chain():
    """Test 6: Does the video fallback chain work (Sora 2 -> Veo 3.1)?"""
    print("\n=== TEST 6: Video Fallback Chain ===")
    from mcp.types import TextContent

    call_log = []

    async def mock_sora(*args, **kwargs):
        call_log.append("Sora 2")
        raise Exception("OpenAI Sora rate limited")

    async def mock_veo(*args, **kwargs):
        call_log.append("Veo 3.1")
        return [TextContent(type="text", text="Generated by Veo 3.1 fallback")]

    with patch('tools.mcp_server.generate_sora_video_mcp', mock_sora), \
         patch('tools.mcp_server.generate_veo_text_to_video_mcp', mock_veo):

        from tools.mcp_server import generate_video_with_fallback
        result = asyncio.run(generate_video_with_fallback(
            prompt="test video", filename="test.mp4"
        ))

    if call_log == ["Sora 2", "Veo 3.1"]:
        print(f"  Call order: {' -> '.join(call_log)}")
        print(f"  Final result from: Veo 3.1 (backup)")
        print("  PASS - Video fallback works correctly")
        return True
    else:
        print(f"  FAIL - Unexpected call order: {call_log}")
        return False


def test_logging_setup():
    """Test 7: Is loguru configured with file + stderr outputs?"""
    print("\n=== TEST 7: Logging Configuration ===")
    from loguru import logger

    handlers = logger._core.handlers
    handler_count = len(handlers)

    log_file = Path(__file__).parent.parent / "logs" / "mcp_server.log"
    file_exists = log_file.exists()

    print(f"  Active handlers: {handler_count}")
    print(f"  Log file exists: {file_exists} ({log_file})")

    if file_exists:
        size = log_file.stat().st_size
        print(f"  Log file size: {size} bytes")

    passed = handler_count >= 2 and file_exists
    print(f"  {'PASS' if passed else 'FAIL'}")
    return passed


def test_no_print_statements():
    """Test 8: Are all print() statements gone?"""
    print("\n=== TEST 8: No Remaining print() Calls ===")
    source = Path(__file__).parent / "mcp_server.py"
    content = source.read_text(encoding='utf-8')

    lines_with_print = []
    for i, line in enumerate(content.split('\n'), 1):
        stripped = line.strip()
        # Skip comments and strings
        if stripped.startswith('#'):
            continue
        if 'print(' in stripped and 'file=sys.stderr' in stripped:
            lines_with_print.append((i, stripped[:80]))

    if not lines_with_print:
        print(f"  Zero print(file=sys.stderr) found")
        print("  PASS - All migrated to loguru")
        return True
    else:
        print(f"  FAIL - {len(lines_with_print)} print() calls remain:")
        for line_num, text in lines_with_print[:5]:
            print(f"    Line {line_num}: {text}")
        return False


if __name__ == "__main__":
    print("=" * 55)
    print("  MCP SERVER RELIABILITY TEST SUITE")
    print("=" * 55)

    tests = [
        test_imports,
        test_retry_decorators,
        test_retry_actually_retries,
        test_retry_gives_up_after_max,
        test_fallback_chain,
        test_video_fallback_chain,
        test_logging_setup,
        test_no_print_statements,
    ]

    results = []
    for test in tests:
        try:
            results.append(test())
        except Exception as e:
            print(f"  FAIL (exception): {e}")
            results.append(False)

    passed = sum(results)
    total = len(results)

    print("\n" + "=" * 55)
    print(f"  RESULTS: {passed}/{total} tests passed")
    if passed == total:
        print("  ALL TESTS PASSED - Reliability features verified")
    else:
        print(f"  {total - passed} test(s) FAILED - needs attention")
    print("=" * 55)
