"""SessionStart hook: recreate the local MCP setup inside Claude Code cloud sessions.

No-op unless CLAUDE_CODE_REMOTE=true, so local sessions are untouched.

In the cloud container it:
  1. Writes .mcp.json from config/mcp.cloud.json, keeping only servers whose
     required env vars are set (secrets come from the cloud environment's
     variables; the file itself holds only ${VAR} placeholders).
  2. Auto-approves those project MCP servers via .claude/settings.local.json.
  3. Installs marketing-tools' Python deps into a private venv when that
     server is enabled (the system Python has Debian-managed packages pip
     cannot upgrade).

An existing .mcp.json is only overwritten if this hook generated it.
"""

import json
import os
import subprocess
import sys
from pathlib import Path

ROOT = Path(os.environ.get("CLAUDE_PROJECT_DIR") or Path(__file__).resolve().parents[2])
TEMPLATE = ROOT / "config" / "mcp.cloud.json"
MCP_PATH = ROOT / ".mcp.json"
LOCAL_SETTINGS = ROOT / ".claude" / "settings.local.json"
CACHE = Path.home() / ".cache" / "test_agents"
MARKER = CACHE / "mcp_cloud_generated"
VENV = CACHE / "marketing-tools-venv"
VENV_PY = VENV / "bin" / "python"

# Server -> env vars that must be set for it to be useful.
REQUIRED_ENV = {
    "perplexity": ["PERPLEXITY_API_KEY"],
    "bright-data": ["BRIGHTDATA_API_TOKEN"],
    "n8n-mcp": ["N8N_API_URL", "N8N_API_KEY"],
    "sequential-thinking": [],
    "marketing-tools": ["OPENAI_API_KEY"],
}

MARKETING_DEPS = ["mcp<2", "openai", "httpx", "tenacity", "loguru", "python-dotenv", "google-genai"]


def log(msg):
    print(f"[cloud-mcp] {msg}", file=sys.stderr)


def write_mcp_json():
    if MCP_PATH.exists() and not MARKER.exists():
        log(".mcp.json exists and was not generated by this hook; leaving it alone")
        return None

    servers = json.loads(TEMPLATE.read_text())["mcpServers"]
    enabled, skipped = {}, []
    for name, cfg in servers.items():
        missing = [v for v in REQUIRED_ENV.get(name, []) if not os.environ.get(v)]
        if missing:
            skipped.append(f"{name} (needs {', '.join(missing)})")
        else:
            enabled[name] = cfg

    MCP_PATH.write_text(json.dumps({"mcpServers": enabled}, indent=2) + "\n")
    MARKER.parent.mkdir(parents=True, exist_ok=True)
    MARKER.touch()
    log(f"enabled: {', '.join(enabled) or 'none'}")
    if skipped:
        log(f"skipped: {'; '.join(skipped)}")
    return enabled


def approve_servers(names):
    settings = {}
    if LOCAL_SETTINGS.exists():
        try:
            settings = json.loads(LOCAL_SETTINGS.read_text())
        except json.JSONDecodeError:
            log("settings.local.json is not valid JSON; not touching it")
            return
    settings["enableAllProjectMcpServers"] = True
    settings["enabledMcpjsonServers"] = sorted(set(settings.get("enabledMcpjsonServers", [])) | set(names))
    LOCAL_SETTINGS.write_text(json.dumps(settings, indent=2) + "\n")


def install_marketing_deps():
    """Return True when VENV_PY can run marketing-tools."""
    check = [str(VENV_PY), "-c", "import mcp, openai, tenacity, loguru, dotenv"]
    if VENV_PY.exists() and subprocess.run(check, capture_output=True).returncode == 0:
        return True
    log("installing marketing-tools Python deps")
    steps = [
        ["uv", "venv", "--quiet", "--allow-existing", str(VENV)],
        ["uv", "pip", "install", "--quiet", "--python", str(VENV_PY), *MARKETING_DEPS],
    ]
    for cmd in steps:
        result = subprocess.run(cmd, capture_output=True, text=True)
        if result.returncode != 0:
            log(f"{' '.join(cmd[:3])} failed:\n{result.stderr[-2000:]}")
            return False
    return True


def main():
    if os.environ.get("CLAUDE_CODE_REMOTE") != "true":
        return
    enabled = write_mcp_json()
    if enabled is None:
        return
    if "marketing-tools" in enabled:
        if install_marketing_deps():
            enabled["marketing-tools"]["command"] = str(VENV_PY)
        else:
            del enabled["marketing-tools"]
        MCP_PATH.write_text(json.dumps({"mcpServers": enabled}, indent=2) + "\n")
    approve_servers(enabled)


if __name__ == "__main__":
    main()
