"""
VOICE_TEAM Factory — Post-Deploy Setup Validator

Smoke-tests a firm's setup BEFORE real calls arrive:
  1. Loads the firm.yml
  2. Generates a synthetic test email intent from a mock call
  3. Runs the SAME validation rules the voice_email_gate.ps1 hook enforces
     (no vendor leaks, required sections, [Firm Name] subject prefix)
  4. Optionally also creates a real test calendar event you can delete after

If any validation fails, the firm is NOT demo-ready. Fix and re-run.

Usage:
    python validate_firm_setup.py memory/firms/sterling_legal.yml
    python validate_firm_setup.py memory/firms/sterling_legal.yml --create-test-calendar

Author: VOICE_TEAM Factory
"""

from __future__ import annotations

import json
import re
import sys
from datetime import datetime, timedelta, timezone
from pathlib import Path
from typing import Any

if hasattr(sys.stdout, "reconfigure"):
    sys.stdout.reconfigure(encoding="utf-8")
    sys.stderr.reconfigure(encoding="utf-8")

import yaml

# Import the email-intent builder from the booking script so we test the same
# function that runs in production.
sys.path.insert(0, str(Path(__file__).parent))
from book_pending_consults import build_email_intent  # type: ignore

REPO_ROOT = Path(__file__).resolve().parents[2]
VOICE_TEAM = REPO_ROOT / "VOICE_TEAM"


# --- Validation rules (mirror voice_email_gate.ps1) ----------------------

FORBIDDEN_VENDOR_TERMS = [
    "retell", "retellai", "dashboard.retellai",
    "gpt-realtime", "openai-realtime",
    "11labs", "elevenlabs", "cartesia", "minimax", "deepgram", "twilio",
]
REQUIRED_SECTIONS = ["Caller", "Incident", "Action Required"]
SUBJECT_PREFIX_RE = re.compile(r"^\[[^\]]+\]")


def find_vendor_term(text: str) -> str | None:
    low = (text or "").lower()
    for term in FORBIDDEN_VENDOR_TERMS:
        if term in low:
            return term
    return None


def validate_intent(intent: dict) -> tuple[bool, list[str], list[str]]:
    """Return (passed, errors, warnings)."""
    errors: list[str] = []
    warnings: list[str] = []
    email = intent.get("email", {})
    subject = email.get("subject", "")
    body = email.get("body_markdown", "")
    to = email.get("to", "")

    # 1. Vendor leak in subject
    v = find_vendor_term(subject)
    if v:
        errors.append(f"Subject contains forbidden vendor term: '{v}'")

    # 2. Vendor leak in body
    v = find_vendor_term(body)
    if v:
        errors.append(f"Body contains forbidden vendor term: '{v}' (breaks white-label)")

    # 3. Subject prefix
    if not SUBJECT_PREFIX_RE.match(subject):
        errors.append(f"Subject must start with '[<Firm Name>]'. Got: '{subject}'")

    # 4. Required sections
    body_low = body.lower()
    for section in REQUIRED_SECTIONS:
        if section.lower() not in body_low:
            errors.append(f"Body missing required section: '{section}'")

    # 5. Recipient sanity
    if not to or "@" not in to:
        errors.append(f"Email recipient is invalid: '{to}'")

    # Soft warnings
    if len(body) > 8000:
        warnings.append(f"Body is long ({len(body)} chars) — attorneys may skim past key info")
    if len(body) < 400:
        warnings.append(f"Body is short ({len(body)} chars) — probably missing structured data")
    if not email.get("urls", {}).get("recording"):
        warnings.append("No recording URL in email.urls.recording — attorneys can't listen")

    return len(errors) == 0, errors, warnings


# --- Synthetic test call --------------------------------------------------

def fake_call_fields(firm: dict) -> dict[str, Any]:
    """Build a realistic mock-call data dict matching what extract_booking_fields produces."""
    return {
        "call_id": "TEST_validate_firm_setup_synthetic",
        "caller_name": "Test Caller",
        "callback_phone": "(555) 000-0000",
        "incident_type": "Test scenario — synthetic call",
        "incident_date": "yesterday",
        "currently_injured": "Yes - receiving medical care",
        "fault_assessment": "Other driver",
        "police_report_filed": "Yes",
        "insurance_contact": "Has already spoken with insurance",
        "preferred_day": "tomorrow",
        "preferred_time": "2pm",
        "urgency": "this_week",
        "case_quality": "strong",
        "outside_practice": False,
        "call_summary": "Synthetic test call generated by validate_firm_setup.py.",
        "transcript": "",
        "recording_url": "https://example.com/test-recording.wav",
        "recording_multi_channel_url": "https://example.com/test-multi.wav",
        "public_log_url": "https://example.com/test.log",
        "dashboard_call_url": "",  # Intentionally empty to test missing-URL handling
        "call_duration_sec": 180,
    }


# --- Main ----------------------------------------------------------------

def main():
    if len(sys.argv) < 2:
        print("Usage: python validate_firm_setup.py <firm.yml path> [--create-test-calendar]", file=sys.stderr)
        sys.exit(1)

    firm_path = Path(sys.argv[1])
    if not firm_path.is_absolute():
        firm_path = (Path.cwd() / firm_path).resolve()
    if not firm_path.exists():
        print(f"FATAL: firm.yml not found at {firm_path}", file=sys.stderr)
        sys.exit(1)

    firm_doc = yaml.safe_load(firm_path.read_text(encoding="utf-8"))
    firm = firm_doc["firm"]
    print(f"\n=== Validating setup: {firm['name']} ({firm['slug']}) ===\n")

    # Step 1: deployment artifact must exist
    deploy_artifact = VOICE_TEAM / "outputs" / "deployments" / f"{firm['slug']}_s2s.json"
    deploy_artifact_alt = VOICE_TEAM / "outputs" / "deployments" / f"{firm['slug']}.json"
    if not deploy_artifact.exists() and not deploy_artifact_alt.exists():
        print(f"  [FAIL] No deployment artifact found. Run deploy first.")
        sys.exit(1)
    print(f"  [PASS] Deployment artifact exists")

    # Step 2: firm.yml has required fields
    required_top_keys = ["firm", "retell", "intake", "post_call_analysis"]
    missing_keys = [k for k in required_top_keys if k not in firm_doc]
    if missing_keys:
        print(f"  [FAIL] firm.yml missing top-level sections: {missing_keys}")
        sys.exit(1)
    print(f"  [PASS] firm.yml has all required top-level sections")

    # Step 3: phone number is bound
    phone = firm_doc.get("retell", {}).get("phone_number") or ""
    if not phone.startswith("+"):
        print(f"  [FAIL] Phone number not in E.164 format: '{phone}'")
        sys.exit(1)
    print(f"  [PASS] Phone number in E.164 format: {phone}")

    # Step 4: generate synthetic email intent + validate
    print(f"\n  Generating synthetic email intent for validation...")
    fields = fake_call_fields(firm)
    slot_dt = datetime.now(tz=timezone.utc) + timedelta(days=1)
    try:
        result = build_email_intent(firm_doc, fields, slot_dt, fields["call_id"], dry_run=True)
        intent = result["intent"]
        intent_path = result["intent_path"]
        print(f"  [PASS] Synthetic intent generated: {intent_path}")
    except Exception as e:
        print(f"  [FAIL] build_email_intent raised: {e}")
        sys.exit(1)

    # Step 5: run validation rules against the intent
    print(f"\n  Running validation rules (mirrors voice_email_gate.ps1)...")
    passed, errors, warnings = validate_intent(intent)

    if errors:
        print(f"\n  [FAIL] {len(errors)} ERROR(S):")
        for e in errors:
            print(f"    ✗ {e}")
    if warnings:
        print(f"\n  [WARN] {len(warnings)} WARNING(S):")
        for w in warnings:
            print(f"    ! {w}")

    if not passed:
        print(f"\n=== ❌ VALIDATION FAILED — fix the errors above and re-run ===\n")
        sys.exit(1)

    print(f"\n  [PASS] All validation rules passed")

    # Step 6 (optional): create a test calendar event
    if "--create-test-calendar" in sys.argv:
        print(f"\n  --create-test-calendar requested. To actually create the calendar event,")
        print(f"  hand off to Claude Code with this command:")
        print(f'    "Use voice-deployer to create a test calendar event for {firm["slug"]} from the synthetic intent."')

    print(f"\n=== ✅ {firm['name']} SETUP VALIDATED — demo-ready ===")
    print(f"\n  Next:")
    print(f"    1. Place a real test call to {phone}")
    print(f"    2. Run: python tools/book_pending_consults.py --firm {firm['slug']}")
    print(f"    3. Have Claude Code dispatch the booking + email intents")
    print(f"    4. Verify calendar event + email landed as expected\n")


if __name__ == "__main__":
    main()
