"""Validate exports in staging and publish managed files with rollback on failure."""
from __future__ import annotations

import os
import shutil
from pathlib import Path

TEXT_SUFFIXES = {".md", ".json", ".py", ".ps1", ".txt", ".yaml", ".yml", ".toml", ".env", ".js", ".ts", ".css", ".html", ".svg", ".sh"}


def equivalent(source: Path, destination: Path) -> bool:
    """Ignore Git checkout newline conversion for generated text files."""
    if not destination.is_file():
        return False
    first, second = source.read_bytes(), destination.read_bytes()
    if source.suffix.lower() in TEXT_SUFFIXES:
        first, second = first.replace(b"\r\n", b"\n"), second.replace(b"\r\n", b"\n")
    return first == second


def differing_files(stage: Path, destination: Path) -> list[str]:
    """Compare generated bytes, including obsolete generated agent files."""
    expected = {p.relative_to(stage) for p in stage.rglob("*") if p.is_file()}
    obsolete = {p.relative_to(destination) for p in (destination / "agents").rglob("*.md")} - expected
    changed = {p for p in expected if not equivalent(stage / p, destination / p)}
    return sorted(p.as_posix() for p in changed | obsolete)


def publish(stage: Path, destination: Path, backup: Path) -> None:
    """Publish only staged files; restore old bytes if any replacement fails.

    This is rollback-safe, not a filesystem-wide atomic snapshot for readers.
    Native hooks and local settings absent from staging remain untouched.
    """
    stage, destination, backup = stage.resolve(), destination.resolve(), backup.resolve()
    if stage == destination or backup == destination or backup.is_relative_to(destination):
        raise ValueError("Staging and backup must be separate from the destination")
    expected = {p.relative_to(stage) for p in stage.rglob("*") if p.is_file()}
    files = sorted(p for p in expected if not equivalent(stage / p, destination / p))
    stale = sorted({p.relative_to(destination) for p in (destination / "agents").rglob("*.md")} - expected)
    changed: list[tuple[Path, bool]] = []
    try:
        for relative in files + stale:
            target = destination / relative
            if not target.resolve().is_relative_to(destination):
                raise ValueError(f"Generated destination escapes root: {relative}")
            existed = target.exists()
            if existed:
                saved = backup / relative
                saved.parent.mkdir(parents=True, exist_ok=True)
                shutil.copy2(target, saved)
            changed.append((relative, existed))
            target.parent.mkdir(parents=True, exist_ok=True)
            if relative in files:
                os.replace(stage / relative, target)
            else:
                target.unlink()
    except Exception:
        for relative, existed in reversed(changed):
            target = destination / relative
            if existed:
                shutil.copy2(backup / relative, target)
            else:
                target.unlink(missing_ok=True)
        raise
